//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassAttendanceDate
    {
        public int ID { get; set; }
        public string Date { get; set; }
        public string Date1 { get; set; }
        public string Date2 { get; set; }
        public string Date3 { get; set; }
        public string Date4 { get; set; }
        public string Date5 { get; set; }
        public string Date6 { get; set; }
        public string Date7 { get; set; }
        public string Date8 { get; set; }
        public string Date9 { get; set; }
        public string Date10 { get; set; }
        public string Date11 { get; set; }
        public string Date12 { get; set; }
        public string Date13 { get; set; }
        public string Date14 { get; set; }
        public string Date15 { get; set; }
        public string Date16 { get; set; }
        public string Date17 { get; set; }
        public string Date18 { get; set; }
        public string Date19 { get; set; }
        public string Date20 { get; set; }
        public Nullable<int> HowMany { get; set; }
    }
}
