//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_12_09_Export
    {
        public Nullable<double> ClassID { get; set; }
        public string ClassName { get; set; }
        public string CourseID { get; set; }
        public string Semester { get; set; }
        public string ClassStatus { get; set; }
        public string Keyword { get; set; }
        public string Program { get; set; }
        public string Teacher { get; set; }
        public Nullable<double> Enrolled { get; set; }
        public string Classroom { get; set; }
        public string Location { get; set; }
        public string Times { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<double> HoursPerWeek { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> NumWeeks { get; set; }
        public string Description { get; set; }
        public string Days { get; set; }
        public string Building { get; set; }
        public Nullable<double> NumCompleted { get; set; }
        public Nullable<double> NumRegistered { get; set; }
        public string Class_Site { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
