//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRegistrationHistory
    {
        public int UniqID { get; set; }
        public int ID { get; set; }
        public Nullable<int> NameID { get; set; }
        public int TID { get; set; }
        public int SID { get; set; }
        public int VID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AttendeeType { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Attended { get; set; }
        public Nullable<bool> Attended1 { get; set; }
        public Nullable<bool> Attended2 { get; set; }
        public Nullable<bool> Attended3 { get; set; }
        public Nullable<bool> Attended4 { get; set; }
        public Nullable<bool> Attended5 { get; set; }
        public Nullable<bool> Attended6 { get; set; }
        public Nullable<bool> Attended7 { get; set; }
        public Nullable<bool> Attended8 { get; set; }
        public Nullable<bool> Attended9 { get; set; }
        public Nullable<bool> Attended10 { get; set; }
        public Nullable<bool> Attended11 { get; set; }
        public Nullable<bool> Attended12 { get; set; }
        public Nullable<bool> Attended13 { get; set; }
        public Nullable<bool> Attended14 { get; set; }
        public Nullable<bool> Attended15 { get; set; }
        public Nullable<bool> Attended16 { get; set; }
        public Nullable<bool> Attended17 { get; set; }
        public Nullable<bool> Attended18 { get; set; }
        public Nullable<bool> Attended19 { get; set; }
        public Nullable<bool> Attended20 { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Ethnicity { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ActualCount { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<double> TotalHours { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
