//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int UniqID { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SkillsWanted { get; set; }
        public string Frequency { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> PurchasedHardware_Software { get; set; }
        public string Work_School { get; set; }
        public string Personal { get; set; }
        public string Family { get; set; }
        public string Internet { get; set; }
        public string OtherProjects { get; set; }
        public string Community { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string LastModifiedBy { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
