//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorHistory
    {
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> DonationDateRequested { get; set; }
        public Nullable<decimal> AmountRequested { get; set; }
        public Nullable<System.DateTime> DonationRefusedDate { get; set; }
        public Nullable<System.DateTime> DonationReceivedDate { get; set; }
        public Nullable<decimal> DonationAmount { get; set; }
        public Nullable<int> DonationCheckNum { get; set; }
        public string DonationBankNum { get; set; }
        public string DonationAcctCode { get; set; }
        public string DonationContactPerson { get; set; }
        public string DonationNotes { get; set; }
        public Nullable<System.DateTime> InkindDateRequested { get; set; }
        public string InKindItemRequest { get; set; }
        public Nullable<System.DateTime> InKindDateReceived { get; set; }
        public Nullable<System.DateTime> InKindDateRefused { get; set; }
        public string InKindItemsReceived { get; set; }
        public string InKindContactPerson { get; set; }
        public string InKindNotes { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpDesc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string LastModifiedBy { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
