//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairHour
    {
        public int UniqID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> PairHours { get; set; }
        public Nullable<System.DateTime> DateMet { get; set; }
        public Nullable<double> HoursMet { get; set; }
        public string Activity { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
