//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pairs_export_12_09
    {
        public Nullable<double> PairID { get; set; }
        public Nullable<double> StudentID { get; set; }
        public Nullable<double> TutorID { get; set; }
        public string PairStatus { get; set; }
        public string Program { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> TotalMonths { get; set; }
        public Nullable<double> MonthsActive { get; set; }
        public string TutorDays { get; set; }
        public string TutorTimes { get; set; }
        public string TutorPlace { get; set; }
        public string DateCreated { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
