//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryActiveFFLStudentReport
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TutorFName { get; set; }
        public string TutorLName { get; set; }
        public Nullable<System.DateTime> DissolveDate { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public string Child1Name { get; set; }
        public string Child1Gender { get; set; }
        public Nullable<System.DateTime> Child1DateBorn { get; set; }
        public string Child2Name { get; set; }
        public string Child2Gender { get; set; }
        public Nullable<System.DateTime> Child2DateBorn { get; set; }
        public string Child3Name { get; set; }
        public string Child3Gender { get; set; }
        public Nullable<System.DateTime> Child3DateBorn { get; set; }
        public string Child4Name { get; set; }
        public string Child4Gender { get; set; }
        public Nullable<System.DateTime> Child4DateBorn { get; set; }
        public string Child5Name { get; set; }
        public string Child5Gender { get; set; }
        public Nullable<System.DateTime> Child5DateBorn { get; set; }
        public string Child6Name { get; set; }
        public string Child6Gender { get; set; }
        public Nullable<System.DateTime> Child6DateBorn { get; set; }
        public string Child7Name { get; set; }
        public string Child7Gender { get; set; }
        public Nullable<System.DateTime> Child7DateBorn { get; set; }
        public string Child8Name { get; set; }
        public string Child8Gender { get; set; }
        public Nullable<System.DateTime> Child8DateBorn { get; set; }
        public string Child9Name { get; set; }
        public string Child9Gender { get; set; }
        public Nullable<System.DateTime> Child9DateBorn { get; set; }
        public string Child10Name { get; set; }
        public string Child10Gender { get; set; }
        public Nullable<System.DateTime> Child10DateBorn { get; set; }
        public Nullable<bool> Students_Active { get; set; }
        public Nullable<bool> Students_Active_2 { get; set; }
        public Nullable<bool> Family_Literacy { get; set; }
    }
}
