//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryActiveFFLPair
    {
        public string Students_Salutation { get; set; }
        public string Students_FirstName { get; set; }
        public string Students_LastName { get; set; }
        public string Students_Address1 { get; set; }
        public string Students_Address2 { get; set; }
        public string Students_City { get; set; }
        public string Students_State { get; set; }
        public string Students_Zip { get; set; }
        public Nullable<System.DateTime> Child1DateBorn { get; set; }
        public Nullable<System.DateTime> Child2DateBorn { get; set; }
        public Nullable<System.DateTime> Child3DateBorn { get; set; }
        public Nullable<System.DateTime> Child4DateBorn { get; set; }
        public Nullable<System.DateTime> Child5DateBorn { get; set; }
        public Nullable<System.DateTime> Child6DateBorn { get; set; }
        public string Students_Keyword { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Students_Program { get; set; }
        public int Students_ID { get; set; }
        public int SID { get; set; }
        public int TID { get; set; }
        public int Tutors_ID { get; set; }
        public string Tutors_Salutation { get; set; }
        public string Tutors_FirstName { get; set; }
        public string Tutors_LastName { get; set; }
        public string Tutors_Address1 { get; set; }
        public string Tutors_Address2 { get; set; }
        public string Tutors_City { get; set; }
        public string Tutors_State { get; set; }
        public string Tutors_Zip { get; set; }
        public string Tutors_Keyword { get; set; }
        public string Tutors_Program { get; set; }
        public string Students_Ethnicity { get; set; }
        public string Tutors_Ethnicity { get; set; }
        public string Tutors_NativeLanguage { get; set; }
        public string Students_NativeLanguage { get; set; }
    }
}
