//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryClassAttendanceList
    {
        public int ID { get; set; }
        public string SessionName { get; set; }
        public string SessionDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Instructors { get; set; }
        public string Comments { get; set; }
        public Nullable<double> SessionLength { get; set; }
        public string Expr1 { get; set; }
        public string CourseID { get; set; }
        public string Semester { get; set; }
        public string ClassStatus { get; set; }
        public string Keyword { get; set; }
        public string Program { get; set; }
        public string Teacher { get; set; }
        public Nullable<double> Enrolled { get; set; }
        public string Classroom { get; set; }
        public string Location { get; set; }
        public string Times { get; set; }
        public Nullable<double> Hours { get; set; }
        public Nullable<double> HoursPerWeek { get; set; }
        public Nullable<double> NumWeeks { get; set; }
        public string Description { get; set; }
        public string Days { get; set; }
        public string Building { get; set; }
        public Nullable<double> NumCompleted { get; set; }
        public Nullable<double> NumRegistered { get; set; }
        public string Class_Site { get; set; }
        public string myName { get; set; }
        public string Date { get; set; }
        public string Date1 { get; set; }
        public string Date2 { get; set; }
        public string Date3 { get; set; }
        public string Date4 { get; set; }
        public string Date5 { get; set; }
        public string Date6 { get; set; }
        public string Date7 { get; set; }
        public string Date8 { get; set; }
        public string Date9 { get; set; }
        public string Date10 { get; set; }
        public string Date11 { get; set; }
        public string Date12 { get; set; }
        public string Date13 { get; set; }
        public string Date14 { get; set; }
        public string Date15 { get; set; }
        public string Date16 { get; set; }
        public string Date17 { get; set; }
        public string Date18 { get; set; }
        public string Date19 { get; set; }
        public string Date20 { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string AttendeeType { get; set; }
        public string Home { get; set; }
        public string Work { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<bool> Attended { get; set; }
        public Nullable<bool> Attended1 { get; set; }
        public Nullable<bool> Attended2 { get; set; }
        public Nullable<bool> Attended3 { get; set; }
        public Nullable<bool> Attended4 { get; set; }
        public Nullable<bool> Attended5 { get; set; }
        public Nullable<bool> Attended6 { get; set; }
        public Nullable<bool> Attended7 { get; set; }
        public Nullable<bool> Attended8 { get; set; }
        public Nullable<bool> Attended9 { get; set; }
        public Nullable<bool> Attended10 { get; set; }
        public Nullable<bool> Attended11 { get; set; }
        public Nullable<bool> Attended12 { get; set; }
        public Nullable<bool> Attended13 { get; set; }
        public Nullable<bool> Attended14 { get; set; }
        public Nullable<bool> Attended15 { get; set; }
        public Nullable<bool> Attended16 { get; set; }
        public Nullable<bool> Attended17 { get; set; }
        public Nullable<bool> Attended18 { get; set; }
        public Nullable<bool> Attended19 { get; set; }
        public Nullable<bool> Attended20 { get; set; }
        public Nullable<int> HowMany { get; set; }
        public Nullable<int> ActualCount { get; set; }
    }
}
