//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryContact
    {
        public int ID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExt { get; set; }
        public string FAXAreaCode { get; set; }
        public string FAX { get; set; }
        public string CellAreaCode1 { get; set; }
        public string CellPhone1 { get; set; }
        public string CellAreaCode2 { get; set; }
        public string CellAreaPhone2 { get; set; }
        public string ContactPref { get; set; }
        public string EMail { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public string ContactType { get; set; }
        public string Referral { get; set; }
        public string MailCode { get; set; }
        public string Program { get; set; }
        public string Category { get; set; }
        public string Keyword { get; set; }
        public string Status { get; set; }
        public string CallLocation { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public string InActiveReason { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpDesc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string LastModifiedBy { get; set; }
        public string Hyperlink1 { get; set; }
        public string Hyperlink2 { get; set; }
        public string Hyperlink3 { get; set; }
        public string Hyperlink4 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
