//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryPairsMetMoreThan12Hours2
    {
        public string TutorName { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<System.DateTime> DissolveDate { get; set; }
        public string PairStatus { get; set; }
        public Nullable<System.DateTime> DateMet { get; set; }
        public Nullable<double> HoursMet { get; set; }
        public string Activity { get; set; }
        public int UniqID { get; set; }
        public int TID { get; set; }
        public int SID { get; set; }
    }
}
