//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qrySmallGroupRegistrationHistory
    {
        public Nullable<int> ID { get; set; }
        public int RegistrationHistoryID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> VID { get; set; }
        public string SmallGroupRegistrationHistory_Status { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string CellPhone1 { get; set; }
        public string Email { get; set; }
        public string AttendeeType { get; set; }
        public string SmallGroupRegistrationHistory_Status_2 { get; set; }
    }
}
