//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryTutorFollowUpToday
    {
        public string Name { get; set; }
        public string Home { get; set; }
        public string Work { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpDesc { get; set; }
        public int ID { get; set; }
        public string LastModifiedBy { get; set; }
        public int UniqID { get; set; }
    }
}
