//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryTutor
    {
        public int ID { get; set; }
        public Nullable<int> LitProID { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public string WorkPhoneExt { get; set; }
        public string FAXAreaCode { get; set; }
        public string FAX { get; set; }
        public string CellAreaCode1 { get; set; }
        public string CellPhone1 { get; set; }
        public string CellAreaCode2 { get; set; }
        public string CellAreaPhone2 { get; set; }
        public string ContactPref { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> FingerPrintDate { get; set; }
        public string Source { get; set; }
        public string Staff { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string ActiveType { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public string InActiveReason { get; set; }
        public Nullable<System.DateTime> FirstActive { get; set; }
        public string MailCode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public string Occupation { get; set; }
        public string EmergContact { get; set; }
        public string EmergAreaCode { get; set; }
        public string EmergPhone { get; set; }
        public string Employer { get; set; }
        public string EmployerStatus { get; set; }
        public string Referral { get; set; }
        public string Keyword { get; set; }
        public string Category { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpDesc { get; set; }
        public string Program { get; set; }
        public Nullable<bool> C1_1Tutoring { get; set; }
        public Nullable<bool> C_1 { get; set; }
        public Nullable<bool> C_2 { get; set; }
        public Nullable<bool> C_3 { get; set; }
        public Nullable<bool> Family_Literacy { get; set; }
        public Nullable<bool> FFL_1 { get; set; }
        public Nullable<bool> FFL_2 { get; set; }
        public Nullable<bool> FFL_3 { get; set; }
        public Nullable<bool> CompLab { get; set; }
        public Nullable<bool> Lab1 { get; set; }
        public Nullable<bool> Lab2 { get; set; }
        public Nullable<bool> Lab3 { get; set; }
        public Nullable<bool> OpenLab { get; set; }
        public Nullable<bool> SmallGroups { get; set; }
        public Nullable<bool> InHouse { get; set; }
        public Nullable<bool> LPT { get; set; }
        public Nullable<bool> C411 { get; set; }
        public Nullable<bool> ESL { get; set; }
        public Nullable<bool> Reading_Sharing { get; set; }
        public Nullable<bool> OffSite { get; set; }
        public Nullable<bool> Project90 { get; set; }
        public Nullable<bool> Jericho { get; set; }
        public Nullable<bool> Bayshore { get; set; }
        public Nullable<bool> Headstart { get; set; }
        public Nullable<bool> AdultSchool { get; set; }
        public string Income { get; set; }
        public string TutorContact { get; set; }
        public string StudentPreference { get; set; }
        public string LocationPref { get; set; }
        public string LocationPref2 { get; set; }
        public string LocationPref3 { get; set; }
        public string Transportation { get; set; }
        public string InterestHobbies { get; set; }
        public string SmokingPref { get; set; }
        public string StudentSmoker { get; set; }
        public string CallLocation { get; set; }
        public string SpecialInstructions { get; set; }
        public string NativeLanguage { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public string FirstCalledBy { get; set; }
        public Nullable<System.DateTime> FirstCalledByDate { get; set; }
        public string HowHeard { get; set; }
        public Nullable<System.DateTime> WelcomePacketSentDate { get; set; }
        public string WhyProjRead { get; set; }
        public Nullable<bool> AvailMonAM { get; set; }
        public Nullable<bool> AvailMonPM { get; set; }
        public Nullable<bool> AvailMonEVE { get; set; }
        public Nullable<bool> AvailTueAM { get; set; }
        public Nullable<bool> AvailTuePM { get; set; }
        public Nullable<bool> AvailTueEVE { get; set; }
        public Nullable<bool> AvailWedAM { get; set; }
        public Nullable<bool> AvailWedPM { get; set; }
        public Nullable<bool> AvailWedEVE { get; set; }
        public Nullable<bool> AvailThuAM { get; set; }
        public Nullable<bool> AvailThuPM { get; set; }
        public Nullable<bool> AvailThudEVE { get; set; }
        public Nullable<bool> AvailFriAM { get; set; }
        public Nullable<bool> AvailFriPM { get; set; }
        public Nullable<bool> AvailFriEVE { get; set; }
        public Nullable<bool> AvailSatAM { get; set; }
        public Nullable<bool> AvailSatPM { get; set; }
        public Nullable<bool> AvailSatEVE { get; set; }
        public Nullable<bool> AvailSunAM { get; set; }
        public Nullable<bool> AvailSunPM { get; set; }
        public Nullable<bool> AvailSunEVE { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<int> PairID { get; set; }
        public string Hyperlink1 { get; set; }
        public string Hyperlink2 { get; set; }
        public string Hyperlink3 { get; set; }
        public string Hyperlink4 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string Home { get; set; }
        public string Work { get; set; }
        public string Cell1 { get; set; }
        public string Cell2 { get; set; }
    }
}
