//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryWorkshopRegistrationHistoryALL
    {
        public string SessionName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string SessionType { get; set; }
        public Nullable<float> WorkshopLength { get; set; }
        public int ID { get; set; }
        public Nullable<int> NameID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> SID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AttendeeType { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<bool> Attended { get; set; }
        public string Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public string FollowUpDesc { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string LastModifiedBy { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
