//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesAndGoal
    {
        public int ID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> GoalSet { get; set; }
        public Nullable<System.DateTime> MakingProgress { get; set; }
        public Nullable<System.DateTime> GoalMet { get; set; }
    }
}
