//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallGroupRegistrationHistory
    {
        public Nullable<int> ID { get; set; }
        public int RegistrationHistoryID { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> SID { get; set; }
        public Nullable<int> VID { get; set; }
        public string AttendeeType { get; set; }
        public string Status { get; set; }
    }
}
