//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmallGroupRegistrationHour
    {
        public int RegistrationHoursID { get; set; }
        public Nullable<int> RegistrationHistoryID { get; set; }
        public Nullable<System.DateTime> AttendancePeriodEndDate { get; set; }
        public Nullable<float> Hours { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
        public string Comments { get; set; }
        public string SmallGroupRegistrationStatus { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
