//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Export_12_09
    {
        public Nullable<double> StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<double> Zip { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public string Instructions { get; set; }
        public string Mail { get; set; }
        public string Status { get; set; }
        public string Keyword { get; set; }
        public string Program { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<double> Age { get; set; }
        public string Employed { get; set; }
        public string Occupation { get; set; }
        public string Employer { get; set; }
        public string LastGrade { get; set; }
        public string Medical { get; set; }
        public string Problems { get; set; }
        public Nullable<double> MonthsActive { get; set; }
        public string ReasonLeft { get; set; }
        public string Site { get; set; }
        public string Birthplace { get; set; }
        public Nullable<double> NumChildren { get; set; }
        public string SourceType { get; set; }
        public string SourceName { get; set; }
        public string Smoker { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Staff { get; set; }
        public string AgeRange { get; set; }
        public string AdultSchool { get; set; }
        public string Email { get; set; }
        public string EmergencyWho { get; set; }
        public string EmergencyPhone { get; set; }
        public string Interests { get; set; }
        public Nullable<double> YoungestKidAge { get; set; }
        public Nullable<double> NumChildrenPreK { get; set; }
        public Nullable<double> NumChildrenK6 { get; set; }
        public Nullable<double> TempLongInt1 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
