//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditTrail
    {
        public int AuditID { get; set; }
        public string ID { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<System.DateTime> TimeChanged { get; set; }
        public string Tutor { get; set; }
        public string Student { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Computer { get; set; }
        public string Employee { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
