//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatusHistory
    {
        public int AutoID { get; set; }
        public Nullable<int> ID { get; set; }
        public string StudentorTutor { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<System.DateTime> ChangedDateTime { get; set; }
        public string ChangedBy { get; set; }
    }
}
