//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor_Export_12_09
    {
        public Nullable<double> TutorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<double> Zip { get; set; }
        public string HomeAreaCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkAreaCode { get; set; }
        public string WorkPhone { get; set; }
        public string C3rdPhoneAreaCode { get; set; }
        public string C3rdPhone { get; set; }
        public string WorkExt { get; set; }
        public string TutorStatus { get; set; }
        public string Keyword { get; set; }
        public string Program { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Mail { get; set; }
        public string Instructions { get; set; }
        public string EmergencyWho { get; set; }
        public string EmergencyPhone { get; set; }
        public string Salutation { get; set; }
        public string Employed { get; set; }
        public string Company { get; set; }
        public string Occupation { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<double> Age { get; set; }
        public string AgeRange { get; set; }
        public string Birthplace { get; set; }
        public string InstructionMode { get; set; }
        public string Interests { get; set; }
        public string Smoker { get; set; }
        public Nullable<System.DateTime> IntakeDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<double> TotalMonths { get; set; }
        public Nullable<double> MonthsActive { get; set; }
        public string Staff { get; set; }
        public string WhatExpect { get; set; }
        public string Problems { get; set; }
        public string ReasonLeft { get; set; }
        public string SourceName { get; set; }
        public string TrainingStatus { get; set; }
        public Nullable<double> MonthsCumulative { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
