//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitProRead.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorQuarterlyStartingNum
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateProduced { get; set; }
        public Nullable<int> LastQuarterNum { get; set; }
        public Nullable<int> TotalInstructed { get; set; }
        public Nullable<int> TotalTrained { get; set; }
    }
}
